version: 0.0
os: linux
files:
  - source: moodle/
    destination: /var/www/html/moodle
hooks:
  BeforeInstall:
    - location: deployment-scripts/install-dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: deployment-scripts/start-server.sh
      timeout: 300
      runas: root